### PR TITLE
KON-174: Added and applied coding standards

### PR DESCRIPTION
**Pull request by rimi-itk**

### CODE REVIEW

**Comment by tuj** [comment]
Can we allow closing ; in javascript?

**Comment by rimi-itk** [comment]
> Can we require closing ; in javascript instead of removing all?

Yes, but do we want to waste time and space on typing unnecessary `;`s?

**Comment by tuj** [comment]
Yes, because it is easier to read the code.

**Comment by cableman** [comment]
I it's a statement, yes ...

Statements;
```
var tmp = function tmp() { 
   bla bla ; 
};
var t = 1;
```

Not statement
```
function temp() {
  blabla;
}
var t = 'test´;
```

**Pull request merged**
